### ISSUE TITLE
Mod triggers on teleports

### ISSUE THREAD

**Issue by gaussandhisgun** [someElseIsHere/sonicboom#1]
This is a really cool mod, adds a certain sense of immersion, especially if your character is a near-immortal multidimensional cyborg or whatever. BUT the mod triggers at anything remotely close to a teleport: entities and players going to sleep in beds, endermen teleporting around, ender pearls and other stuff like that. Maybe its possible to make the mod only work on players that are currently flying with an elytra?

**Comment by Rozbiynk** [comment]
also explosions from mobs are annoying

**Comment by onePlaceholder** [comment]
oki

**Comment by onePlaceholder** [comment]
and sorry for the lateness

**Comment by onePlaceholder** [comment]
done

**Comment by MadCow667** [comment]
Make a config option?
