### ISSUE TITLE
Please fix game version filing on modrinth for "v2.7 - Fabric - 1.20.1" to not be listed as a 1.21 mod. 

### ISSUE THREAD

**Issue by Ynaught** [someElseIsHere/sonicboom#7]
I am referring to [Sonic Boom 2.7 - Fabric - 1.20.1](https://modrinth.com/mod/sonic-boom/version/uOF8NnYU). I think you accidently left a checkbox ticked or something as the site-upload states it's for game version 1.20.1–1.21 despite the file name suggesting it's just for 1.20.1.

This is problematic for mod managers that help users update mods they downloaded automatically. Currently. . . Sonic Boom 2.7 - Fabric - 1.20.1 is the newest listed version of the mod for 1.21. . . despite the version not being made for, nor does it even work on, mc 1.21.

**Comment by onePlaceholder** [comment]
sorry it's now fixed
